// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback to local socket connection if env is broken, or just force it for this environment
    url: process.env["DATABASE_URL"]?.startsWith("prisma+postgres")
      ? "postgres://jmaharyuda@localhost:5432/revas_db"
      : process.env["DATABASE_URL"],
  },
});
